files:
  include: "src/static/stylesheets/*.scss"
  ignore:
    - "src/static/stylesheets/reset.scss"
rules:
  class-name-format:
    - 2
    - convention: hyphenatedbem
  leading-zero:
    - 0
  quotes:
    - 1
    - style: double
  nesting-depth:
    - 1
    - max-depth: 3


